# Generated by Django 4.1.7 on 2023-05-20 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_options_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название опции')),
            ],
            options={
                'verbose_name': 'Опция товара',
                'verbose_name_plural': 'Опции товаров',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='productoption',
            options={'verbose_name': 'Опция, связанная с товаром', 'verbose_name_plural': 'Опции, связанные с товаром'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='options',
        ),
        migrations.AddField(
            model_name='productoption',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество товара с данной опцией'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Товар'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20, verbose_name='Вариант опции')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.productoption', verbose_name='Опция')),
            ],
            options={
                'verbose_name': 'Значение опции',
                'verbose_name_plural': 'Значения опций товаров',
                'ordering': ['option'],
                'unique_together': {('option', 'value')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='option_values',
            field=models.ManyToManyField(through='shop.ProductOption', to='shop.optionvalue', verbose_name='Опции'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='option_value',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.optionvalue', verbose_name='Значение опции'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='productoption',
            unique_together={('option_value', 'product')},
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='variants',
        ),
    ]
