# Generated by Django 4.1.7 on 2023-05-20 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_option_alter_productoption_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionvalue',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.option', verbose_name='Опция'),
        ),
    ]
