# Generated by Django 4.1.7 on 2023-05-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CRE', 'Создан'), ('PAI', 'Оплачен'), ('COL', 'Собран'), ('DEL', 'В доставке'), ('PIC', 'Готов к выдаче'), ('REC', 'Получен'), ('CAN', 'Отменён')], default='CRE', max_length=3, verbose_name='Статус заказа'),
        ),
    ]
