# Generated by Django 4.1.7 on 2023-05-19 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание турнира')),
                ('tournament_tickets', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tickets.tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Турнир',
                'verbose_name_plural': 'Турниры',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='ClubInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание клуба')),
                ('club_tickets', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tickets.club', verbose_name='Клуб')),
            ],
            options={
                'verbose_name': 'Клуб',
                'verbose_name_plural': 'Клубы',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Текст статьи')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('clubs', models.ManyToManyField(blank=True, to='info.clubinfo', verbose_name='Клубы, относящиеся к статье')),
                ('tournaments', models.ManyToManyField(blank=True, to='info.tournamentinfo', verbose_name='Турниры, относящиеся к статье')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['pk'],
            },
        ),
    ]
