# Generated by Django 4.1.7 on 2023-05-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default='2023-05-24 14:52:14.605427 +00:00', verbose_name='Время создания'),
            preserve_default=False,
        ),
    ]
