# Generated by Django 4.1.7 on 2023-05-15 19:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Название клуба')),
                ('slug', models.SlugField(max_length=15, unique=True, verbose_name='URL')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clubs/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Футбольный клуб',
                'verbose_name_plural': 'Футбольные клубы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FanCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Полное имя')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Карта болельщика',
                'verbose_name_plural': 'Карты болельщика',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_match', models.DateTimeField(verbose_name='Время проведения')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
                'ordering': ['datetime_match'],
            },
        ),
        migrations.CreateModel(
            name='MatchClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_home', models.BooleanField(default=False, verbose_name='Домашний матч')),
            ],
            options={
                'verbose_name': 'Клуб, участвующий в матче',
                'verbose_name_plural': 'Клубы, участвующие в матче',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField()),
                ('place', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'ordering': ['p_sector'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название сектора')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='URL')),
                ('side', models.CharField(db_index=True, max_length=20, verbose_name='Сторона на схеме')),
            ],
            options={
                'verbose_name': 'Сектор',
                'verbose_name_plural': 'Секторы',
                'ordering': ['sec_stadium'],
            },
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название стадиона')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('places', models.FileField(null=True, upload_to='stadiums', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json'])], verbose_name='JSON-файл для генерации мест')),
            ],
            options={
                'verbose_name': 'Стадион',
                'verbose_name_plural': 'Стадионы',
                'ordering': ['city'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_sale', models.BooleanField(default=True, verbose_name='В продаже')),
                ('price', models.PositiveIntegerField(verbose_name='Цена билета')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
                'ordering': ['t_match__datetime_match', 'on_sale'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Название турнира')),
                ('slug', models.SlugField(max_length=15, unique=True, verbose_name='URL')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tournaments/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Турнир',
                'verbose_name_plural': 'Турниры',
                'ordering': ['name'],
            },
        ),
    ]
